### ISSUE TITLE
Wishbone and IPbus BFMs.

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM#70]
Is anyone working on Wishbone or IPbus BFM?
I could contribute but I don't want to duplicate the work.

**Comment by UVVM** [comment]
Hi,

Really good to hear that you would like to contribute 😊
A Wishbone interface is already being worked on.
To my knowledge nobody is working on an IPbus BFM, so that would be great.

To your information we will open up a dedicated repository for community VIP (BFM and/or VVC) within a couple of weeks.

- Espen

Fra: m-kru <notifications@github.com>
Sendt: 24. januar 2019 18:26
Til: UVVM/UVVM <UVVM@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [UVVM/UVVM] Wishbone and IPbus BFMs. (#70)


Is anyone working on Wishbone or IPbus BFM?
I could contribute but I don't want to duplicate the work.

**Comment by m-kru** [comment]
Ok, then I am going to work on IPbus.

**Comment by EspenTallaksen** [comment]
Great 😊

- Espen

Fra: m-kru <notifications@github.com>
Sendt: 27. januar 2019 17:04
Til: UVVM/UVVM <UVVM@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: Re: [UVVM/UVVM] Wishbone and IPbus BFMs. (#70)


Ok, then I am going to work on IPbus.

**Comment by m-kru** [comment]
What is the concept for using external modules? I would like to reuse some of the IPbus code, but I am not sure how I should do that. Should I just copy necessary files, provide it as git submodule or maybe set some path variable to the IPbus directory?

**Comment by UVVM** [comment]
I think it is a good idea to use git submodule to include external modules into your VIP as you suggest.

We have just created a new repository "UVVM_Community_VIPs", where the UVVM community can share their own work. Would you like to become a collaborator on this repository?

- Andre

**Comment by m-kru** [comment]
Yes, I would. By the way, why do you create separate repository for community VIPs? Why you do not want to keep everything in single repository?

**Comment by m-kru** [comment]
@UVVM Can you take a look at https://github.com/ipbus/ipbus-firmware/issues/91 and leave a comment?

**Comment by UVVM** [comment]
Regarding why we have a separate repository for community VIPs: 
We have been a bit back and forth on this question, but we ended up on two separate repositories to make life easier for both us and the collaborators. The main reason is that we cannot take any ownership of submitted VIPs (for e.g. testing and verification).

By separating the UVVM and UVVM Community VIPs repositories we let the community maintain ownership of their own VIPs, and they can choose themselves if they wish to update their VIPs and whether or not they wish to submit a verification suite for their code. However, we encourage users to submit pull-requests for improvements in the main UVVM repository.
